CREATE TABLE ACCOUNT(
	ID_USER SERIAL UNIQUE PRIMARY KEY NOT NULL,
	U_NAME VARCHAR(25) NOT NULL,
	U_EMAIL VARCHAR(25) UNIQUE NOT NULL,
	U_PASSWORD VARCHAR(25) NOT NULL,
	U_ROLE VARCHAR(25)
);

CREATE TABLE WALLET(
	ID_WALLET SERIAL UNIQUE PRIMARY KEY NOT NULL,
	ID_USER SERIAL UNIQUE NOT NULL,
	CONSTRAINT FK_USER FOREIGN KEY(ID_USER) REFERENCES ACCOUNT(ID_USER) ON DELETE CASCADE ON UPDATE CASCADE,
	W_BALANCE INT
);

CREATE TABLE FILM(
	ID_FILM SERIAL UNIQUE PRIMARY KEY NOT NULL,
	FILM_NAME VARCHAR(25),
	FILM_DURATION INT,
	FILM_PRICE INT,
	FILM_SELLING INT
);

CREATE TABLE CATEGORY(
	ID_CATEGORY SERIAL UNIQUE PRIMARY KEY NOT NULL,
	CATEGORY_NAME VARCHAR(25) NOT NULL
);

CREATE TABLE FILMCATEGORY(
	ID_FILM SERIAL NOT NULL,
	CONSTRAINT FK_FILM FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM) ON DELETE CASCADE ON UPDATE CASCADE,
	ID_CATEGORY SERIAL NOT NULL,
	CONSTRAINT FK_CATEGORY FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FILMSCHEDULE(
	ID_SCHEDULE SERIAL UNIQUE PRIMARY KEY NOT NULL,
	ID_FILM SERIAL NOT NULL,
	CONSTRAINT FK_FILM FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM) ON UPDATE CASCADE ON DELETE CASCADE,
	SCHEDULE_DATE VARCHAR(25) NOT NULL,
	SCHEDULE_TIME VARCHAR(25) NOT NULL,
	SCHEDULE_PRICE INT NOT NULL
);

CREATE TABLE SEAT(
	ID_SEAT SERIAL UNIQUE PRIMARY KEY NOT NULL,
	SEAT_NUMBER VARCHAR(5) UNIQUE NOT NULL
);

CREATE TABLE ORDERS(
	ID_ORDER SERIAL UNIQUE PRIMARY KEY NOT NULL,
	ID_USER SERIAL NOT NULL,
	CONSTRAINT FK_USER FOREIGN KEY(ID_USER) REFERENCES ACCOUNT(ID_USER) ON DELETE CASCADE ON UPDATE CASCADE,
	ID_SCHEDULE SERIAL NOT NULL,
	CONSTRAINT FK_SCHEDULE FOREIGN KEY(ID_SCHEDULE) REFERENCES FILMSCHEDULE(ID_SCHEDULE) ON DELETE CASCADE ON UPDATE CASCADE,
	ORDER_SEAT VARCHAR(25) NOT NULL,
	ORDER_DATE VARCHAR(25) NOT NULL,
	ORDER_QTY INT NOT NULL,
	ORDER_TOTAL INT NOT NULL
);

CREATE TABLE ORDERSEAT(
	ID_ORDER SERIAL NOT NULL,
	CONSTRAINT FK_ORDER FOREIGN KEY(ID_ORDER) REFERENCES ORDERS(ID_ORDER) ON UPDATE CASCADE ON DELETE CASCADE,
	ID_SEAT SERIAL NOT NULL,
	CONSTRAINT FK_SEAT FOREIGN KEY(ID_SEAT) REFERENCES SEAT(ID_SEAT) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PAYMENTS(
	ID_PAYMENT SERIAL UNIQUE PRIMARY KEY NOT NULL,
	ID_ORDER SERIAL NOT NULL,
	CONSTRAINT FK_ORDER FOREIGN KEY(ID_ORDER) REFERENCES ORDERS(ID_ORDER) ON DELETE CASCADE ON UPDATE CASCADE,
	ORDER_TOTAL INT NOT NULL,
	PAYMENT_STATUS VARCHAR(25) NOT NULL
);